# Consider the different input formats

## List of Array-like

- This is the format that matplotlib's eventplot accepts
- Each array contains the spiketimes for one neuron
- error-prone in needing to maintain seperate index of neuron IDs and to add per-spike features

In [2]:
import numpy as np

In [53]:
n_neurons = 5
duration = 1000 # ms
max_spikes = 10 # per neuron
min_spikes = 1 # per neuron
spike_times = [np.sort(np.random.randint(0, duration, size=np.random.randint(min_spikes, max_spikes_per))) for _ in range(n_neurons)]

In [54]:
spike_times

[array([  0,  45, 261, 386, 442, 633, 847, 892]),
 array([167, 314, 331, 390, 632, 724, 778, 828, 854]),
 array([630, 808, 893, 904]),
 array([135, 208, 226, 542, 732, 919]),
 array([127, 158, 258, 522])]

## Gridded

- largest data footprint
- often, people convert to spike times before plotting

In [56]:
import torch
a = torch.load('spiketensor.pt')

In [59]:
a[1,:,:] # trial 1

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

## Tabular

- medium data footprint
- neuron IDs stays with spike
- easy to add per-spike features
- pandas DF used by Allen/NWB (along with xarray for other histogram purposes)

In [61]:
import sys; sys.path.insert(0, '../..')
from scripts.simdata import sim_spikes

spikes_df2 = sim_spikes(num_neurons=20, firing_rate=1, duration=100)
spikes_df2.head()

time neuron
0  0.019186     15
1  0.071529      3
2  0.074711      7
3  0.171826     14
4  0.202786      3